version: '3.8'
services:
  app:
    image: 'spring-postgres:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - db
    ports:
      - "8877:8877"
  db:
    container_name: postgresqlDb
    image: postgres:14.0-alpine
    restart: on-failure
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    
