package com.example.monitor.management.common;

public enum AppLogEvent {

    MONITORING_APP_STARTED,
    CREATE_REQUEST_RECEIVED,
    FETCH_REQUEST_RECEIVED,
    EDIT_REQUEST_RECEIVED,
    DELETE_REQUEST_RECEIVED,
    LOGIN_REQUEST_RECEIVED,
    CREATE_RESPONSE_SENT,
    FETCH_RESPONSE_SENT,
    EDIT_RESPONSE_SENT,
    DELETE_RESPONSE_SENT,
    LOGIN_RESPONSE_SENT,
    LOGIN_SERVICE_STARTED,
    REMOVE_DOCUMENT_SERVICE_STARTED,
    REMOVE_DOCUMENT_SERVICE_FINISHED,
    UPDATE_DOCUMENT_SERVICE_STARTED,
    UPDATE_DOCUMENT_SERVICE_FINISHED,
    CREATE_DOCUMENT_SERVICE_STARTED,
    CREATE_DOCUMENT_SERVICE_FINISHED,
    RETRIEVE_DOCUMENT_SERVICE_STARTED,
    RETRIEVE_ALL_DOCUMENTS_SERVICE_STARTED,
    RETRIEVE_ALL_DOCUMENTS_SERVICE_FINISHED;


    @Override
    public String toString() {
        return this.name();
    }
}
