app:
  jwt:
    token-expiration-minutes: 60
    secret-key: BMmbDWpwfa2rPaOuXHAiZQWnkuNzksiCFOjKhTSecyyRet

com:
  monitoring:
    application:
      version: 0.0.1
server:
  servlet:
    context-path: /api/v1
  port: 8877

spring:

  application:
    name: monitoring-management
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5432/monitoring?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 123@abc
  jpa:
    show-sql: false
    open-in-view: false
    properties:

      hibernate.format_sql: true
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      #      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: monitoring

    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  flyway:
      baselineOnMigrate: true
      enabled: true
      schemas: monitoring
      default-schema: monitoring
      locations: classpath:db.migration

